question_data = [
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "When was &quot;Garry&#039;s Mod&quot; released?", "correct_answer": "December 24, 2004",
     "incorrect_answers": ["November 13, 2004", "December 13, 2004", "November 12, 2004"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "When was the game &#039;Portal 2&#039; released?", "correct_answer": "2011",
     "incorrect_answers": ["2014", "2009", "2007"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Rocket League is a game which features..", "correct_answer": "Cars",
     "incorrect_answers": ["Helicopters", "Planes", "Submarines"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In &quot;Overwatch&quot;, what is the name of Mercy&#039;s &quot;ultimate ability&quot;?",
     "correct_answer": "Valkyrie", "incorrect_answers": ["Earthshatter", "Rocket Barrage", "Molten Core"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Who was the main antagonist of Max Payne 3 (2012)?", "correct_answer": "Victor Branco",
     "incorrect_answers": ["&Aacute;lvaro Neves", "Armando Becker", "Milo Rego"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What year was the game Dishonored released?", "correct_answer": "2012",
     "incorrect_answers": ["2011", "2008", "2013"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "How many total monsters appear in Monster Hunter Generations?", "correct_answer": "105",
     "incorrect_answers": ["100", "98", "73"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In what year was Garry&#039;s Mod released as a standalone title on Valve&#039;s Steam distribution service?",
     "correct_answer": "2006", "incorrect_answers": ["2007", "2004", "2003"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In Pokemon Red &amp; Blue, what is the name of HM05?", "correct_answer": "Flash",
     "incorrect_answers": ["Strength", "Cut", "Fly"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In the video game &quot;League of Legends&quot; which character is known as &quot;The Sinister Blade&quot;?",
     "correct_answer": "Katarina", "incorrect_answers": ["Shaco", "Akali", "Zed"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "Mortal Kombat was almost based on Jean-Claude Van Damme movie.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Super Mario World&quot;, the rhino mini-boss, Reznor, is named after the lead singer of the band &quot;Nine Inch Nails&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of the first level in &quot;Call of Duty: World at War&quot;?",
     "correct_answer": "Semper Fi", "incorrect_answers": ["Ring of Steel", "Vendetta", "Eviction"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Who developed the 2016 farming RPG &quot;Stardew Valley&quot;?", "correct_answer": "Eric Barone",
     "incorrect_answers": ["Daisuke Amaya", "Jasper Byrne", "Lucas Pope"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In the PAYDAY series, who is the iconic leader of the PAYDAY gang?", "correct_answer": "Dallas",
     "incorrect_answers": ["Wolf", "Chains", "Hoxton"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "Shang Tsung is a playable character in Mortal Kombat XL.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following Zelda games did not feature Ganon as a final boss?",
     "correct_answer": "Majora&#039;s Mask",
     "incorrect_answers": ["Ocarina of Time", "Skyward Sword", "Breath of the Wild"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following is not a character in the video game Doki Doki Literature Club?",
     "correct_answer": "Nico", "incorrect_answers": ["Monika", "Natsuki", "Sayori"]}
]
